import { useEffect, useRef, useState } from 'react'
import { Copy } from 'lucide-react'
import { motion } from 'motion/react'
import { useTypewriter } from './useTypewriter'

const VIDEO = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260530_042513_df96a13b-6155-4f6e-8b93-c9dee66fba08.mp4'

export function DocsExperience() {
  const video = useRef<HTMLVideoElement>(null); const { displayed, done } = useTypewriter('Welcome to Aura.dev. Tell the CEO what success looks like, and your team will plan, execute, review, and report back.'); const [copied, setCopied] = useState(false)
  useEffect(() => { let previousX = 0; let seeking = false; let target = 0; const seek = () => { const element = video.current; if (!element || !element.duration || seeking) return; seeking = true; element.currentTime = target }; const move = (event: MouseEvent) => { const element = video.current; if (!element || innerWidth < 768 || !element.duration) return; const delta = event.clientX - previousX; previousX = event.clientX; target = Math.max(0, Math.min(element.duration, element.currentTime + delta / innerWidth * .8 * element.duration)); seek() }; const sought = () => { seeking = false; const element = video.current; if (element && Math.abs(element.currentTime - target) > .02) seek() }; addEventListener('mousemove', move); video.current?.addEventListener('seeked', sought); return () => { removeEventListener('mousemove', move); video.current?.removeEventListener('seeked', sought) } }, [])
  const copy = async () => { await navigator.clipboard?.writeText('hello@aura.dev'); setCopied(true); setTimeout(() => setCopied(false), 1500) }
  const actions = ['Start a task', 'Invite my team', 'Read the docs', 'See the workflow']
  return <section id="docs" className="relative h-screen overflow-hidden px-5 pb-12 pt-28 sm:px-8 md:flex md:items-center md:px-10 md:pb-0"><video ref={video} muted playsInline preload="auto" className="fixed inset-0 -z-10 h-full w-full object-cover object-[70%_center]" src={VIDEO}/><div className="absolute inset-0 -z-10 bg-white/30"/><div className="docs-nav"><div className="docs-logo"><span>Aura.dev</span><b>✳︎</b></div><div className="docs-links"><a href="#teams">Teams</a>, <a href="#how-it-works">Workflows</a>, <a href="#specialists">Specialists</a>, <a href="#docs">Docs</a></div><a href="#contact">Talk to us</a></div><div className="relative z-10 max-w-xl"><p className="mb-5 select-none text-[clamp(18px,4vw,26px)] leading-[1.3] blur-[4px]">Meet A.R.I.A.,<br/>Aura's Adaptive Routing Intelligence Agent</p><p className="mb-5 min-h-[54px] text-[clamp(18px,4vw,26px)] font-normal leading-[1.35]">{displayed}{!done && <span className="inline-block w-[2px] h-[1.1em] bg-black align-middle ml-[2px] animate-blink"/>}</p><motion.div initial={{ opacity: 0, y: 8 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .4, duration: .4 }} className="flex flex-wrap gap-y-1">{actions.map(action => <a href="#top" key={action} className="docs-action">{action}</a>)}<button onClick={copy} className="docs-contact">{copied ? 'Copied' : <>Reach us: <u>hello@aura.dev</u></>}<Copy size={12}/></button></motion.div></div></section>
}
