import { Plus } from 'lucide-react'
import { motion } from 'motion/react'

const VIDEO = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260508_215831_c6a8989c-d716-4d8d-8745-e972a2eec711.mp4'
const ease = [0.16, 1, 0.3, 1] as const

export function HowItWorks() {
  return <section id="how-it-works" className="how-it-works"><motion.div initial={{ opacity: 0, scale: 1.05 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: 1.8, ease }} className="how-video"><video autoPlay muted playsInline loop src={VIDEO}/></motion.div><motion.nav initial={{ opacity: 0, y: -16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .8, ease }} className="how-nav"><div className="how-brand"><span className="how-logo"><i/><i/></span><b>Aura.dev</b></div><button className="how-menu"><span><Plus size={12} strokeWidth={3}/></span>Menu</button><div className="how-tags"><span>Orchestrated AI</span><span>Independent review</span></div><div className="how-system"><span>◉</span> Adaptive teams</div></motion.nav><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .5, duration: 1, ease }} className="how-footer"><div className="how-main"><motion.p initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .6, duration: .8, ease }} className="how-kicker"><i/> How Aura works</motion.p><motion.h2 initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .8, duration: .8, ease }}>One goal, many<br/>experts. Verified.</motion.h2><motion.div initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 1, duration: .8, ease }} className="how-actions"><a href="#teams">Meet the team</a><a href="#specialists">How it works</a></motion.div></div><div className="how-pills"><span>CEO orchestration</span><span>Department routing</span><span>QA approval</span></div></motion.div></section>
}
