import { useEffect, useRef, useState } from 'react'
import { Check } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'
import { useTypewriter } from './useTypewriter'

const HERO_VIDEO_SRC = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260601_110537_3a579fa0-7bbc-4d94-9d25-0e816c7840f5.mp4'
const services = ['Engineering', 'Research', 'Design', 'Growth']

export function InquiryHero({ onDeploy }: { onDeploy: (capabilities: string[]) => void }) {
  const video = useRef<HTMLVideoElement>(null); const { displayed, done, reduced } = useTypewriter("build your\ndream team."); const [selected, setSelected] = useState<string[]>([])
  useEffect(() => { let previousX = 0; const scrub = (event: MouseEvent) => { const element = video.current; if (reduced || !element || innerWidth < 1024 || !element.duration) return; const delta = event.clientX - previousX; previousX = event.clientX; element.currentTime = Math.max(0, Math.min(element.duration, element.currentTime + (delta / innerWidth) * .8 * element.duration)) }; const mobilePlayback = () => { if (innerWidth < 1024 && video.current) { video.current.autoplay = true; video.current.play().catch(() => undefined) } }; addEventListener('mousemove', scrub); addEventListener('resize', mobilePlayback); mobilePlayback(); return () => { removeEventListener('mousemove', scrub); removeEventListener('resize', mobilePlayback) } }, [reduced])
  const toggle = (service: string) => setSelected(current => current.includes(service) ? current.filter(item => item !== service) : [...current, service])
  const deploy = () => { if (!selected.length) return; onDeploy(selected); document.querySelector('#about')?.scrollIntoView({ behavior: 'smooth' }) }
  return <section id="top" className="relative bg-white text-neutral-900 flex flex-col lg:block lg:min-h-screen"><div className="order-last lg:order-none relative lg:absolute lg:inset-0 lg:z-0 overflow-hidden pointer-events-none w-full aspect-square md:aspect-video lg:aspect-auto lg:h-full bg-neutral-50 lg:bg-transparent"><video ref={video} muted playsInline preload="auto" className="w-full h-full object-cover object-right lg:object-right-bottom" src={HERO_VIDEO_SRC}/></div><div className="relative z-10 flex flex-col order-first lg:order-none w-full bg-white lg:bg-transparent pb-8 lg:pb-0 lg:min-h-screen"><main className="w-full max-w-7xl mx-auto px-6 py-12 pt-32 lg:pt-12 flex-1 flex flex-col justify-center"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><h1 className="text-5xl md:text-6xl lg:text-[76px] font-display font-normal tracking-tight text-black leading-[1.08] mb-8 select-none w-full whitespace-pre-wrap">{displayed}{!done && <span className="inline-block w-[2px] h-[1.1em] bg-black align-middle ml-[2px] animate-blink"/>}</h1></motion.div><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }}><p className="text-lg md:text-xl text-[#5A635A] leading-relaxed font-normal mb-14 max-w-2xl">One CEO agent. Purpose-built departments. Specialists who execute, reviewers who verify, and a single shared record of the work.</p></motion.div><div id="workflows"><h2 className="text-2xl font-medium tracking-tight mb-2">What should your team tackle?</h2><p className="opacity-85 text-[#738273] mb-8">Select all that apply</p><div className="flex flex-wrap gap-2">{services.map(service => { const active = selected.includes(service); return <motion.button whileTap={{ scale: .97 }} key={service} onClick={() => toggle(service)} className={`flex items-center gap-1.5 rounded-full px-4 py-2.5 text-sm ${active ? 'bg-[#1C2E1E] text-white shadow-md shadow-emerald-950/5 transform' : 'bg-white text-[#1C2E1E] border border-[#F1F3F1] hover:bg-[#F1F3F1]/55'}`}>{service}<AnimatePresence>{active && <motion.span initial={{ scale: 0 }} animate={{ scale: 1 }} exit={{ scale: 0 }} transition={{ type: 'spring', stiffness: 300, damping: 20 }}><Check size={14}/></motion.span>}</AnimatePresence></motion.button>})}</div><AnimatePresence mode="wait">{selected.length === 0 ? <motion.p key="empty" initial={{ opacity: 0 }} animate={{ opacity: .5 }} exit={{ opacity: 0 }} className="mt-5 italic text-xs">Choose capabilities above and Aura.dev will staff the right team.</motion.p> : <motion.div key="chosen" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="mt-5 max-w-2xl bg-[#FAFBF9] border border-[#F1F3F1] rounded-2xl p-5">Ready to assemble: {selected.join(', ')}<button onClick={deploy} className="float-right text-[#4D6D47] uppercase text-xs">Let's Go →</button></motion.div>}</AnimatePresence></div></main></div></section>
}
