import { useState } from 'react'
import { ArrowUpRight, X } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'

const VIDEO = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260517_222138_3e3205be-3364-417b-a64a-bfe087acbec4.mp4'
const ease = [0.22, 1, 0.36, 1] as const
const links = ['Story', 'Expertise', 'Studios', 'Feedback']

export function OrgShowcase({ id, mode }: { id: string; mode: 'teams' | 'specialists' }) {
  const [open, setOpen] = useState(false)
  const teams = mode === 'teams'
  const stats = teams ? [['1', 'CEO\nORCHESTRATOR'], ['8', 'DEPARTMENT\nSUPERVISORS'], ['48', 'SPECIALIST\nAGENTS']] : [['5', 'CORE\nSPECIALISTS'], ['12', 'TOOL\nCAPABILITIES'], ['4', 'REVIEW\nGATES']]
  const heading = teams ? ['One', 'Team,', 'Verified.'] : ['Specialists.', 'One', 'Standard.']
  return <section id={id} className="relative isolate min-h-screen overflow-hidden bg-white font-sans text-black flex flex-col uppercase font-semibold tracking-wide"><video autoPlay loop muted playsInline className="absolute inset-0 -z-10 h-full w-full object-cover" src={VIDEO}/><div className="absolute inset-0 -z-10 bg-white/45 backdrop-blur-[1px]"/>
    <div className="flex items-center justify-between px-5 pt-5 sm:px-8 md:px-12 md:pt-6"><motion.div custom={0} initial={{ opacity: 0, y: -20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0, duration: .5, ease }} className="h-8 w-8 rounded-full border-2 border-[#5E0ED7] grid place-items-center"><span className="h-2.5 w-2.5 rounded-full bg-[#5E0ED7]"/></motion.div><div className="hidden md:flex gap-6 text-sm tracking-widest">{links.map((link, index) => <motion.a custom={index + 1} initial={{ opacity: 0, y: -20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (index + 1) * .1, duration: .5, ease }} href={`#${id}`} key={link}>{link}</motion.a>)}</div><motion.button custom={5} initial={{ opacity: 0, y: -20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .5, duration: .5, ease }} onClick={() => setOpen(true)} aria-label="Open department menu" className="grid h-9 w-9 place-content-center gap-1 rounded-full bg-black">{[0,1,2].map(item => <span key={item} className="h-0.5 w-4 bg-white"/>)}</motion.button></div>
    <div className="flex-1 flex items-center justify-end px-5 py-8 sm:px-8 md:px-12 md:py-0"><div className="flex gap-5 text-right sm:gap-8 md:gap-10">{stats.map(([number, label], index) => <motion.div key={number} custom={index + 2} initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (index + 2) * .12, duration: .6, ease }}><div className="font-semibold text-[clamp(1.5rem,5vw,3.5rem)] leading-none"><span className="text-[.5em] text-[#5E0ED7]">+</span>{number}</div><div className="mt-2 whitespace-pre-line text-[10px] leading-tight sm:text-xs md:text-sm">{label}</div></motion.div>)}</div></div>
    <div className="flex flex-col gap-6 px-5 pb-8 sm:px-8 md:gap-12 md:px-12 md:pb-12"><div className="flex items-center justify-between gap-4"><motion.p custom={5} initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .6, duration: .6, ease }} className="max-w-[160px] text-[10px] tracking-widest sm:max-w-xs sm:text-xs md:text-sm">{teams ? <>A COMPANY<br/>OF AGENTS<br/>BUILT TO SHIP</> : <>DEEP EXPERTISE<br/>CLEAR OWNERSHIP<br/>REAL OUTPUTS</>}</motion.p><motion.a custom={6} initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .72, duration: .6, ease }} href="#how-it-works" className="flex items-center gap-1 whitespace-nowrap text-base text-[#5E0ED7] sm:text-xl md:text-2xl">See the system <ArrowUpRight className="h-[18px] w-[18px] sm:h-[22px] sm:w-[22px]"/></motion.a></div><div className="flex items-end justify-between gap-3 sm:gap-4"><motion.p custom={7} initial={{ opacity: 0, y: 32 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: .84, duration: .6, ease }} className="w-[120px] shrink-0 text-left text-[9px] tracking-widest sm:w-[180px] sm:text-xs md:w-[280px] md:text-right md:text-sm">{teams ? 'CEO SETS THE OUTCOME. SUPERVISORS DELEGATE. SPECIALISTS BUILD. INDEPENDENT AGENTS VERIFY.' : 'CODER, EXECUTOR, WEB SURFER, FILE SURFER, AND RAG AGENT: EACH OWNS ONE JOB.'}</motion.p><div className="text-right font-semibold text-[clamp(2rem,9vw,9rem)] leading-[.88]">{heading.map((word, index) => <div key={word} className="overflow-hidden"><motion.div initial={{ y: '110%' }} whileInView={{ y: 0 }} viewport={{ once: true }} transition={{ delay: .4 + index * .14, duration: .7, ease }}>{word}</motion.div></div>)}</div></div></div>
    <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[60] flex flex-col bg-white p-6"><div className="flex justify-between"><div className="h-8 w-8 rounded-full border-2 border-[#5E0ED7] grid place-items-center"><span className="h-2.5 w-2.5 rounded-full bg-[#5E0ED7]"/></div><button onClick={() => setOpen(false)} className="grid h-9 w-9 place-items-center rounded-full bg-black text-white"><X size={18}/></button></div><div className="mt-16 flex flex-col gap-8 text-3xl tracking-widest">{links.map(link => <a onClick={() => setOpen(false)} href={`#${id}`} key={link}>{link}</a>)}</div><a onClick={() => setOpen(false)} href="#contact" className="mt-auto flex items-center gap-1 text-xl text-[#5E0ED7]">Work with Aura <ArrowUpRight/></a></motion.div>}</AnimatePresence>
  </section>
}
